services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    image: stock-frontend:local
    container_name: stock-frontend
    ports:
      - "8088:80"
    networks:
      - stock-net

networks:
  stock-net:
    external: true
    name: stock-net
